
  DROP TABLE IF EXISTS `REGIONS`;
  CREATE TABLE REGIONS(
  REGION_ID NUMERIC(2),
  REGION_NAME VARCHAR(25) NOT NULL,
  CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID) );

  DROP TABLE IF EXISTS `COUNTRIES`;
  CREATE TABLE COUNTRIES (
  COUNTRY_ID VARCHAR(4), 
  COUNTRY_NAME VARCHAR(40),
  REGION_ID  NUMERIC(2),
  CONSTRAINT COUNTRY_ID_PK PRIMARY KEY (COUNTRY_ID),
  CONSTRAINT COUNTRY_REG_FK FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)); 

  DROP TABLE IF EXISTS `LOCATIONS`;
  CREATE TABLE    LOCATIONS (
  LOCATION_ID     NUMERIC(4),
  STREET_ADDRESS  VARCHAR(40),
  POSTAL_CODE     VARCHAR(12), 
  CITY            VARCHAR(30) NOT NULL, 
  STATE_PROVINCE  VARCHAR(25) NULL, 
  COUNTRY_ID      VARCHAR(4),
  CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID),
  CONSTRAINT LOC_ID_FK  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID));

  DROP TABLE IF EXISTS `JOBS`;
  CREATE TABLE JOBS (
  JOB_ID        VARCHAR(10) , 
  JOB_TITLE     VARCHAR(35), 
  MIN_SALARY    NUMERIC(6), 
  MAX_SALARY    NUMERIC(6),
  CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)); 

  DROP TABLE IF EXISTS `DEPARTMENTS`;
  CREATE TABLE    DEPARTMENTS (
  DEPARTMENT_ID    NUMERIC(4), 
  DEPARTMENT_NAME  VARCHAR(30) not null, 
  MANAGER_ID       NUMERIC(6) NULL, 
  LOCATION_ID      NUMERIC(4),
  CONSTRAINT DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID),
  CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID));

  DROP TABLE IF EXISTS `EMPLOYEES`;
  CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID NUMERIC(6) PRIMARY KEY,
  FIRST_NAME VARCHAR(20) not null,
  LAST_NAME VARCHAR(25) not null, 
  EMAIL VARCHAR(25) UNIQUE,
  PHONE_NUMBER VARCHAR(20),
  HIRE_DATE DATE not null,
  JOB_ID VARCHAR(10),
  SALARY NUMERIC(8,2) CHECK (SALARY > 0), 
  COMMISSION_PCT NUMERIC(2,2),
  MANAGER_ID NUMERIC(6),
  DEPARTMENT_ID NUMERIC(4) NULL, 
  CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
  CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
  CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
   );
  
  DROP TABLE IF EXISTS `JOB_HISTORY`; 
  CREATE TABLE JOB_HISTORY (
  EMPLOYEE_ID NUMERIC(6),
  START_DATE    DATE, 
  END_DATE      DATE, 
  JOB_ID        VARCHAR(10),
  DEPARTMENT_ID NUMERIC(4),
  CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE), 
  CONSTRAINT JHIST_DATE_INTERVAL CHECK (end_date > start_date));
  

