
LOAD DATA LOCAL INFILE './regions.csv' \
		INTO TABLE REGIONS \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(REGION_ID,REGION_NAME);

LOAD DATA LOCAL INFILE './country.csv' \
		INTO TABLE COUNTRIES \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(COUNTRY_ID,COUNTRY_NAME,REGION_ID);

LOAD DATA LOCAL INFILE './location.csv' \
		INTO TABLE LOCATIONS \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
                IGNORE 1 LINES \
		(LOCATION_ID,STREET_ADDRESS,POSTAL_CODE,CITY,STATE_PROVINCE,COUNTRY_ID);

LOAD DATA LOCAL INFILE './jobs.csv' \
		INTO TABLE JOBS \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
                IGNORE 1 LINES \
		(JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY);

LOAD DATA LOCAL INFILE './departments.csv' \
		INTO TABLE DEPARTMENTS \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID);

LOAD DATA LOCAL INFILE './employees.csv' \
		INTO TABLE EMPLOYEES \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
	        IGNORE 1 LINES \
		(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,
		MANAGER_ID,DEPARTMENT_ID);

LOAD DATA LOCAL INFILE './job_history.csv' \
		INTO TABLE JOB_HISTORY \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);


