
  DROP TABLE IF EXISTS `DEPARTMENT`;
  CREATE TABLE DEPARTMENT(
  DEPT_ID INT UNSIGNED,
  DEPT_NAME VARCHAR(25) NOT NULL,
  CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPT_ID) );

  DROP TABLE IF EXISTS `EMPLOYEE`;
  CREATE TABLE EMPLOYEE (
  EMP_ID INT UNSIGNED, 
  EMP_NAME VARCHAR(40),
  CONSTRAINT EMP_ID_PK PRIMARY KEY (EMP_ID));

  DROP TABLE IF EXISTS `PAYDETAILS`;
  CREATE TABLE    PAYDETAILS (
  EMP_ID     INT UNSIGNED,
  DEPT_ID    INT UNSIGNED,
  BASIC      INT UNSIGNED, 
  DEDUCTIONS      INT UNSIGNED, 
  ADDITIONS  INT UNSIGNED, 
  DOJ      DATE,
  CONSTRAINT PAYDETAILS_ID_PK PRIMARY KEY (EMP_ID,DEPT_ID),
  CONSTRAINT PAYDETAILS_ID_FK1  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
  CONSTRAINT PAYDETAILS_ID_FK2  FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID));

  DROP TABLE IF EXISTS `PAYROLL`;
  CREATE TABLE PAYROLL (
  EMP_ID        INT UNSIGNED, 
  PAY_DATE     DATE, 
  CONSTRAINT PAYROLL_ID_PK PRIMARY KEY (EMP_ID),
  CONSTRAINT PAYROLL_ID_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID));
