LOAD DATA LOCAL INFILE '~/ISI_LabWork/DBMS/emp.csv' \
		INTO TABLE EMPLOYEE \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(EMP_ID,EMP_NAME);

LOAD DATA LOCAL INFILE '~/ISI_LabWork/DBMS/dept.csv' \
		INTO TABLE DEPARTMENT \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
		IGNORE 1 LINES \
		(DEPT_ID,DEPT_NAME);

LOAD DATA LOCAL INFILE '~/ISI_LabWork/DBMS/paydetails.csv' \
		INTO TABLE PAYDETAILS \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
                IGNORE 1 LINES \
		(EMP_ID,DEPT_ID,BASIC,DEDUCTIONS,ADDITIONS,@var1)
                SET DOJ = STR_TO_DATE(@var1,'%d-%b-%Y');

LOAD DATA LOCAL INFILE '~/ISI_LabWork/DBMS/payroll.csv' \
		INTO TABLE PAYROLL \
		FIELDS TERMINATED BY ',' \
		LINES TERMINATED BY '\n' \
                IGNORE 1 LINES \
		(EMP_ID,@var2)
                SET PAY_DATE = STR_TO_DATE(@var2,'%d-%b-%Y');
